spring:
  application:
    name: mailing-service

  kafka:
    bootstrap-servers: ${KAFKA_ADDR:localhost:9092}
    group-id: email-sender-group-0
    topic-name: email-send-topic

  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8092/eureka/}

server:
  port: ${MAILING_SERVICE_PORT:8084}


